set(_vtk_module_import_prefix "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_depends" "VTK::CommonCore;VTK::CommonMath;VTK::RenderingCore;VTK::RenderingOpenGL2;VTK::RenderingVR;VTK::glew")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_private_depends" "VTK::CommonDataModel;VTK::CommonSystem;VTK::CommonTransforms;VTK::FiltersSources;VTK::ImagingSources;VTK::InteractionWidgets;VTK::jsoncpp;VTK::opengl;VTK::vtksys")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_library_name" "vtkRenderingOpenXR")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRRenderWindow.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRRenderWindowInteractor.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRCamera.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRControlsHelper.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRModel.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRRenderer.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkOpenXRInteractorStyle.h;${_vtk_module_import_prefix}/include/vtkrenderingopenxr-0.1/vtkRenderingOpenXRModule.h")
set_property(TARGET "VTK::RenderingOpenXR" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vtkRenderingOpenXR/vtkRenderingOpenXR-hierarchy.txt")
unset(_vtk_module_import_prefix)
